variable access_key {}
variable secret_key {}
variable region {}
variable vpc_name {}
variable vpc_cidr {}
variable avz {}
variable public_subnet {}
variable public_cidr {}
variable private_subnet {}
variable private_cidr {}
variable ami {}
variable instance_name {}
variable keyname {}